### ISSUE TITLE
NavBar is not using the background colors set by the Appearance Proxy

### ISSUE THREAD

**Issue by JeanMeche** [gklka/GKFadeNavigationController#3]
I use the appearance proxy in my app to have the same navbar colors everywhere in my app. 

The FadeNavigationController stays the original color.

**Comment by gklka** [comment]
GKFadeNavigationController uses a `UIToolbar`, not a `UINavigationBar`. Try change the toolbar's appearance!

**Comment by gklka** [comment]
Changing the color is currently not supported, sorry.
