### ISSUE TITLE
iOS 10 breaks the title and navigation bar buttons

### ISSUE THREAD

**Issue by Pranoy1c** [gklka/GKFadeNavigationController#4]
Everything was working fine with this until iOS 10 when i started facing this issue. Using this causes the title and navigation bar buttons to disappear after a detail view controller is pushed on the navigation controller. more details here. removing it fixes the issue:

http://stackoverflow.com/questions/39212074/ios-10-beta-makes-navigation-bar-buttons-and-title-disappear-on-pushviewcontroll

**Comment by HungPM165** [comment]
Yep, I met the same issue :(

**Comment by gklka** [comment]
Fixed in Release 0.6. Please verify that everything is fine!
