### ISSUE TITLE
iOS 11上发生崩溃

### ISSUE THREAD

**Issue by Rain-dew** [gklka/GKFadeNavigationController#6]
具体来说，是这行代码引起的，似乎在iOS11上模糊不能够在添加子视图？        [_visualEffectView addSubview:shadowView];

- (UIVisualEffectView *)visualEffectView {
    if (!_visualEffectView) {
        // Create a the fake navigation bar background
        UIVisualEffect *blurEffect = [UIBlurEffect effectWithStyle:UIBlurEffectStyleExtraLight];
        
        _visualEffectView = [[UIVisualEffectView alloc] initWithEffect:blurEffect];
        _visualEffectView.frame = CGRectMake(0, -20.f, self.view.frame.size.width, 64.f);
        _visualEffectView.autoresizingMask = UIViewAutoresizingFlexibleWidth;
        _visualEffectView.userInteractionEnabled = NO;
        
        // Shadow line
        UIView *shadowView = [[UIView alloc] initWithFrame:CGRectMake(0, 63.5f, self.view.frame.size.width, 0.5f)];
        shadowView.backgroundColor = [UIColor colorWithWhite:0 alpha:0.2f];
        shadowView.autoresizingMask = UIViewAutoresizingFlexibleWidth;
//        [_visualEffectView addSubview:shadowView];
    }
    
    return _visualEffectView;
}

**Comment by xumeng** [comment]
GKFadeNavigationController Crashing in iOS 11.

*** Assertion failure in -[UIVisualEffectView _addSubview:positioned:relativeTo:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3694.4.18/UIVisualEffectView.m:1464

@gklka

**Comment by gdimoff** [comment]
Crashing badly in iOS 11

**Comment by Rain-dew** [comment]
这写代码干掉就行了

 // Shadow line
  UIView *shadowView = [[UIView alloc] initWithFrame:CGRectMake(0, 63.5f, self.view.frame.size.width, 0.5f)];
  shadowView.backgroundColor = [UIColor colorWithWhite:0 alpha:0.2f];
  shadowView.autoresizingMask = UIViewAutoresizingFlexibleWidth;
// [_visualEffectView addSubview:shadowView];

**Comment by PraveenPali** [comment]
Xcode Version 9.0 (9A235)
objective c
Running on iPhone X Simulator and device in iOS 11


*** Assertion failure in -[UIVisualEffectView _addSubview:positioned:relativeTo:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3694.4.18/UIVisualEffectView.m:1464
2017-10-11 12:04:30.073766+0530 samayla[37484:483806] CRASH: <UITableView: 0x7ffb6895ee00; frame = (93.75 -5.68434e-14; 281.25 487); transform = [-1, -1.2246467991473532e-16, 1.2246467991473532e-16, -1, 0, 0]; clipsToBounds = YES; gestureRecognizers = <NSArray: 0x6040004514c0>; layer = <CALayer: 0x604000420a20>; contentOffset: {0, 0}; contentSize: {281.25, 30}; adjustedContentInset: {0, 0, 0, 0}> has been added as a subview to <UIVisualEffectView: 0x7ffb684806f0; frame = (0 0; 375 667); gestureRecognizers = <NSArray: 0x604000257760>; layer = <CALayer: 0x604000222160>>. Do not add subviews directly to the visual effect view itself, instead add them to the -contentView.
2017-10-11 12:04:30.074149+0530 samayla[37484:483806] Stack Trace: (
	0   CoreFoundation                      0x00000001018fb1cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000106670f41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000101900362 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000103fa8089 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x0000000104b1643f -[UIVisualEffectView _addSubview:positioned:relativeTo:] + 379
	5   samayla                             0x0000000100e4dd73 -[VCFloatingActionButton setupButton] + 2195
	6   samayla                             0x0000000100e4d354 -[VCFloatingActionButton initWithFrame:normalImage:andPressedImage:withScrollview:] + 3108
	7   samayla                             0x0000000100dfccf9 -[ChatViewController viewDidLoad] + 3465
	8   UIKit                               0x00000001046c6d51 -[UIViewController loadViewIfRequired] + 1235
	9   UIKit                               0x00000001046c719e -[UIViewController view] + 27
	10  UIKit                               0x00000001046f913b -[UINavigationController _startCustomTransition:] + 954
	11  UIKit                               0x000000010470f894 -[UINavigationController _startDeferredTransitionIfNeeded:] + 686
	12  UIKit                               0x0000000104710b90 -[UINavigationController __viewWillLayoutSubviews] + 115
	13  UIKit                               0x00000001049672ae -[UILayoutContainerView layoutSubviews] + 231
	14  UIKit                               0x00000001045f7551 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1331
	15  QuartzCore                          0x0000000102f6f4ba -[CALayer layoutSublayers] + 153
	16  QuartzCore                          0x0000000102f735a9 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 401
	17  QuartzCore                          0x0000000102efc1cd _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 365
	18  QuartzCore                          0x0000000102f27ae4 _ZN2CA11Transaction6commitEv + 500
	19  UIKit                               0x0000000104522f4a _UIApplicationFlushRunLoopCATransactionIfTooLate + 167
	20  UIKit                               0x0000000104e7a960 __handleEventQueueInternal + 6894
	21  CoreFoundation                      0x000000010189e2b1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	22  CoreFoundation                      0x000000010193dd31 __CFRunLoopDoSource0 + 81
	23  CoreFoundation                      0x0000000101882c19 __CFRunLoopDoSources0 + 185
	24  CoreFoundation                      0x00000001018821ff __CFRunLoopRun + 1279
	25  CoreFoundation                      0x0000000101881a89 CFRunLoopRunSpecific + 409
	26  GraphicsServices                    0x000000010a0499c6 GSEventRunModal + 62
	27  UIKit                               0x0000000104528d30 UIApplicationMain + 159
	28  samayla                             0x0000000100dc83bf main + 111
	29  libdyld.dylib                       0x0000000106db2d81 start + 1
	30  ???                                 0x0000000000000001 0x0 + 1
)
